### ISSUE TITLE
Issue when running!

### ISSUE THREAD

**Issue by emjimadhu** [eliassjogreen/denon#1]
I ahve imports map and custom tsconfig. 

I usually run this
`deno run -A --importmap=imports.json --config ./tsconfig.json index.ts`

I have `.denonrc.json`

```
{
  "files": [
    "index.ts",
    "src/**/*.ts"
  ],
  "quiet": false,
  "debug": true,
  "fullscreen": true,
  "extensions": [
    "js",
    "ts",
    "json"
  ],
  "match": [
    "*.ts"
  ],
  "skip": [
    "*_test.ts",
    "*_test.js"
  ],
  "interval": 500,
  "watch": [
    "src/"
  ],
  "execute": {
    ".js": ["deno", "run"],
    ".ts": ["deno", "run"]
  }
}
```

When i run this `denon -A --config .denonrc.json --importmap=imports.json index.ts`, i have following error `error: Uncaught #<Object>`

**Comment by eliassjogreen** [comment]
Could you please tell me what version of deno you're running (`deno --version`) and how working directory is structured. When testing i got a ```[DENON] Can not watch directory src/ because it does not exist``` error which is supposed to be thrown because of the config specifying it should watch the `src/` path.

When i change the config file to:
```
{
    "files": ["index.ts"],
    "quiet": false,
    "debug": true,
    "fullscreen": true,
    "extensions": ["js", "ts", "json"],
    "match": ["*.ts"],
    "skip": ["*_test.ts", "*_test.js"],
    "interval": 500,
    "watch": ["./"],
    "execute": {
        ".js": ["deno", "run"],
        ".ts": ["deno", "run"]
    }
}
```
it throws `error: Uncaught #<Object>`.

Will continue to look into this tomorrow.

**Comment by emjimadhu** [comment]
@eliassjogreen 

My Deno Version

```
deno 0.30.0
v8 8.1.108
typescript 3.7.2
```

My folder structure show in screenshot
![Screenshot 2020-01-22 at 3 57 37 PM](https://user-images.githubusercontent.com/15604962/72886655-354a2e80-3d30-11ea-8701-7ad30198ff2c.png)

**Comment by eliassjogreen** [comment]
@emjimadhu 

If you try to reinstall denon and rerun `denon index.ts -- -A --importmap=imports.json --config tsconfig.json` it should work. The `--` is important to distinguish denon flags from deno flags.

**Comment by emjimadhu** [comment]
@eliassjogreen After reinstalling, it does work with the above config. Thanks.
