### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by brianraila** [eliassjogreen/denon#14]
Trying to install denon on my laptop using 

    deno install denon --allow-read --allow-run https://deno.land/x/denon/denon.ts 

But it yields this error

    error TS2345: Argument of type '{ cmd: string[]; }' is not assignable to parameter of type 'RunOptions'.
  Object literal may only specify known properties, and 'cmd' does not exist in type 'RunOptions'.

What could be the issue?

**Comment by eliassjogreen** [comment]
What deno version are you using?

**Comment by brianraila** [comment]
deno v0.36.0

**Comment by brianraila** [comment]
Upgrading to the latest version of Deno 0.39.0 solve the problem.
Thanks.
