### ISSUE TITLE
use the "old" polling watcher as legacy watcher

### ISSUE THREAD

**Issue by ronhippler** [eliassjogreen/denon#19]

**Comment by David-Else** [comment]
Out of interest, why would anyone want to do that? Are we talking about adding back code that became redundant after Deno got  `Deno.watchFs()`? Sound like a really bad idea if that is the case...

**Comment by ronhippler** [comment]
Watching files over network (ftp, ssh) is not possible with the current watchFs. But it uses the notify crate which is able to poll and also to debounce the events.

**Comment by Qu4k** [comment]
Closing as it is already implemented in `rework` branch.  (see db2cc6f43835201317cf5a9e4d77e2b98890aba9)
