### ISSUE TITLE
denon upgrade

### ISSUE THREAD

**Issue by eliassjogreen** [eliassjogreen/denon#26]
A `denon upgrade` command as an alias for `deno install denon -f --allow-read --allow-run https://deno.land/x/denon/denon.ts` would be useful. `denon upgrade` could be able to select version if entered otherwise it would just use latest. This would probably be done with `denon upgrade v1.6.0`

**Comment by MoonSupport** [comment]
Hello!
If is it not urgent, can I try this?

I'm happy to solve this problem!

**Comment by eliassjogreen** [comment]
Sure thing
