### ISSUE TITLE
CLI options are overwritten

### ISSUE THREAD

**Issue by timonson** [eliassjogreen/denon#32]
This is caused by `applyIfDefined` here https://github.com/eliassjogreen/denon/blob/master/denon.ts#L51. For example it overwrites `flags.deno_args` with an empty array (if you don't use a config file). 
I didn't make a PR because there are different logical ways to fix this and I don't know your preference.

**Comment by Qu4k** [comment]
Closing as it is already implemented in rework branch.  (see 4e71708182c302cb9c350b624f0a09629a9eee8d)
