### ISSUE TITLE
Feature Request: Implement Test Directories

### ISSUE THREAD

**Issue by Honga1** [eliassjogreen/denon#35]
## What
Add the ability to select only certain directories for running tests

## Why
Currently when using the flag or config `--test` denon runs `deno test` without an option to select which directories to look and run tests in.

Deno provides this option. ie:
```command
$ deno test src/fetch_test.ts src/signal_test.ts
```

Giving this ability would allow us to have other folders and files in our root directory which are ignored.

## Related files
https://github.com/eliassjogreen/denon/blob/a2d386958a41d21b94875b9ab11b0be2673e502c/denon.ts#L73
![image](https://user-images.githubusercontent.com/33930602/82056969-f7985980-96c2-11ea-81fa-f428d3982708.png)
https://github.com/eliassjogreen/denon/blob/a2d386958a41d21b94875b9ab11b0be2673e502c/denon.ts#L158
![image](https://user-images.githubusercontent.com/33930602/82057001-02eb8500-96c3-11ea-8188-01f6ad0e071a.png)

https://github.com/eliassjogreen/denon/blob/a2d386958a41d21b94875b9ab11b0be2673e502c/cli.ts#L12

## Suggested Solution
To implement this:
1. add another argument to `cli.ts` `deno_test_args`.
2. Remove adding working directory automatically to watch paths
3. Create `config.test_watch` variable in `denon.ts` and use it here:
https://github.com/eliassjogreen/denon/blob/a2d386958a41d21b94875b9ab11b0be2673e502c/denon.ts#L158
4. Add tests

## Background - How I found this issue
I had to use a local `node_modules` folder in a project as I can't quite make the shift over to deno completely yet. This meant that the test runner as it is traversed the `node_modules` directory and tried to run any tests it found there. Causing it to fail.
I solved this by building my own denon by removing the addition of the root directory and adding the `...config.watch` argument to the end of the executor function shown above.

If you agree with the approach above I don't mind implementing this. Let me know.

**Comment by Honga1** [comment]
@eliassjogreen Slight bump for visibility :) 

I can close this if it's not relevant to your design goals.

**Comment by eliassjogreen** [comment]
Yeah it's on the todo for 2.0

**Comment by Qu4k** [comment]
This will be fixed when the `rework` branch is merged.
