### ISSUE TITLE
Error while running - JSON.parse(await readFileStr(file));

### ISSUE THREAD

**Issue by sarthaksavvy** [eliassjogreen/denon#38]
when I run denon I got this error

error: Uncaught SyntaxError: Unexpected token ] in JSON at position 246
    json = JSON.parse(await readFileStr(file));

**Comment by Aslemammad** [comment]
Hello @sarthaksavvy

**Comment by sarthaksavvy** [comment]
It's working but only when I use it on JSON.
Anyways thanks.
