### ISSUE TITLE
Issue with denon command

### ISSUE THREAD

**Issue by ATakaSKY** [eliassjogreen/denon#39]
Installed the command and then ran `denon --alow-net server.ts`, getting the following error:

<img width="744" alt="Screenshot 2020-05-19 at 1 07 00 PM" src="https://user-images.githubusercontent.com/17201629/82298479-d04ad080-99d1-11ea-992f-586a9a1a8858.png">

**Comment by eliassjogreen** [comment]
You have a typo: `--alow-net` needs to be `--allow-net`

**Comment by ATakaSKY** [comment]
Apologies for the typo there. But even after running it with `denon --allow-net server.ts` it yields the same error.

**Comment by eliassjogreen** [comment]
Weird, will be solved in [`2.0.0`](https://github.com/eliassjogreen/denon/milestone/1)
