### ISSUE TITLE
How to properly attach tsconfig.json?

### ISSUE THREAD

**Issue by Tnifey** [eliassjogreen/denon#41]
Hello :)

files:
[https://gist.github.com/Tnifey/5339e42b92348ab45dc96cca27ce9776](https://gist.github.com/Tnifey/5339e42b92348ab45dc96cca27ce9776)

If i run `deno run --config tsconfig.json test.ts`
prints `Decorator loaded [Function: Entity]` without errors

but when I run `denon`
```
[DENON] Watching /mnt/s/test/test.ts, /mnt/s/test
Compile file:///mnt/s/test/test.ts
Decorator loaded [Function: Entity]
error: TS1219 [ERROR]: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' 
option in your 'tsconfig' or 'jsconfig' to remove this warning.
class Entity {
      ~~~~~~
    at file:///mnt/s/test/test.ts:8:7
```
prints error, like there is no tsconfig.json loaded but decorator is working

i tried to change `"--config=tsconfig.json"` in .denon.json to `"--config tsconfig.json"`
but it spits 
```
error: Found argument '--config tsconfig.json' which wasn't expected, or isn't valid in this context
        Did you mean --config?
```

My question is how to properly attach tsconfig.json into .denon.json that it won't print any error?

**Comment by Qu4k** [comment]
This is fixed in `2.0.0` branch with a specific options (`tsconfig`) in the config while declaring an script.
